### ISSUE TITLE
App Crush on start

### ISSUE THREAD

**Issue by omarsherifs** [tcstewart95/step_counter#1]
my app is just crushed once i try to use any of the methods provided in the package

**Comment by tcstewart95** [comment]
Help me get a better feel for what is going wrong, I'd like to help get it up and running. Is there any error code provided with the crash? And are you testing on iOS or Android?

**Comment by tcstewart95** [comment]
I'm guessing that this was an issue with initial configuration, or that it was run on an emulator. If you still want help, just message again.
